# paper-xlsx: the pinned Excel function catalog

"""Worksheet function names Excel recognizes, for the pre-flight linter.

The set is a lint reference, not a gate: an unknown name is a WARNING
(user-defined functions and future Excel functions are legal), so a
missing entry can never break a workbook — it can only mute or raise one
lint finding. Storage-canonical names only: ``_xlfn.``/``_xlws.``
prefixes are stripped by the linter before lookup.
"""

EXCEL_FUNCTIONS = frozenset([
    # math & trig
    "ABS", "ACOS", "ACOSH", "ACOT", "ACOTH", "AGGREGATE", "ARABIC",
    "ASIN", "ASINH", "ATAN", "ATAN2", "ATANH", "BASE", "CEILING",
    "CEILING.MATH", "CEILING.PRECISE", "COMBIN", "COMBINA", "COS",
    "COSH", "COT", "COTH", "CSC", "CSCH", "DECIMAL", "DEGREES", "EVEN",
    "EXP", "FACT", "FACTDOUBLE", "FLOOR", "FLOOR.MATH", "FLOOR.PRECISE",
    "GCD", "INT", "ISO.CEILING", "LCM", "LET", "LN", "LOG", "LOG10",
    "MDETERM", "MINVERSE", "MMULT", "MOD", "MROUND", "MULTINOMIAL",
    "MUNIT", "ODD", "PI", "POWER", "PRODUCT", "QUOTIENT", "RADIANS",
    "RAND", "RANDARRAY", "RANDBETWEEN", "ROMAN", "ROUND", "ROUNDDOWN",
    "ROUNDUP", "SEC", "SECH", "SEQUENCE", "SERIESSUM", "SIGN", "SIN",
    "SINH", "SQRT", "SQRTPI", "SUBTOTAL", "SUM", "SUMIF", "SUMIFS",
    "SUMPRODUCT", "SUMSQ", "SUMX2MY2", "SUMX2PY2", "SUMXMY2", "TAN",
    "TANH", "TRUNC",
    # logical
    "AND", "BYCOL", "BYROW", "FALSE", "IF", "IFERROR", "IFNA", "IFS",
    "LAMBDA", "MAKEARRAY", "MAP", "NOT", "OR", "REDUCE", "SCAN",
    "SWITCH", "TRUE", "XOR",
    # text
    "ARRAYTOTEXT", "ASC", "BAHTTEXT", "CHAR", "CLEAN", "CODE", "CONCAT",
    "CONCATENATE", "DBCS", "DOLLAR", "EXACT", "FIND", "FINDB", "FIXED",
    "JIS", "LEFT", "LEFTB", "LEN", "LENB", "LOWER", "MID", "MIDB",
    "NUMBERVALUE", "PHONETIC", "PROPER", "REPLACE", "REPLACEB", "REPT",
    "RIGHT", "RIGHTB", "SEARCH", "SEARCHB", "SUBSTITUTE", "T", "TEXT",
    "TEXTAFTER", "TEXTBEFORE", "TEXTJOIN", "TEXTSPLIT", "TRIM",
    "UNICHAR", "UNICODE", "UPPER", "VALUE", "VALUETOTEXT",
    # date & time
    "DATE", "DATEDIF", "DATEVALUE", "DAY", "DAYS", "DAYS360", "EDATE",
    "EOMONTH", "HOUR", "ISOWEEKNUM", "MINUTE", "MONTH", "NETWORKDAYS",
    "NETWORKDAYS.INTL", "NOW", "SECOND", "TIME", "TIMEVALUE", "TODAY",
    "WEEKDAY", "WEEKNUM", "WORKDAY", "WORKDAY.INTL", "YEAR", "YEARFRAC",
    # lookup & reference
    "ADDRESS", "AREAS", "CHOOSE", "CHOOSECOLS", "CHOOSEROWS", "COLUMN",
    "COLUMNS", "DROP", "EXPAND", "FILTER", "FORMULATEXT",
    "GETPIVOTDATA", "HLOOKUP", "HSTACK", "HYPERLINK", "IMAGE",
    "INDEX", "INDIRECT", "LOOKUP", "MATCH", "OFFSET", "ROW", "ROWS",
    "RTD", "SORT", "SORTBY", "TAKE", "TOCOL", "TOROW", "TRANSPOSE",
    "UNIQUE", "VLOOKUP", "VSTACK", "WRAPCOLS", "WRAPROWS", "XLOOKUP",
    "XMATCH",
    # statistical
    "AVEDEV", "AVERAGE", "AVERAGEA", "AVERAGEIF", "AVERAGEIFS",
    "BETA.DIST", "BETA.INV", "BETADIST", "BETAINV", "BINOM.DIST",
    "BINOM.DIST.RANGE", "BINOM.INV", "BINOMDIST", "CHIDIST", "CHIINV",
    "CHISQ.DIST", "CHISQ.DIST.RT", "CHISQ.INV", "CHISQ.INV.RT",
    "CHISQ.TEST", "CHITEST", "CONFIDENCE", "CONFIDENCE.NORM",
    "CONFIDENCE.T", "CORREL", "COUNT", "COUNTA", "COUNTBLANK",
    "COUNTIF", "COUNTIFS", "COVAR", "COVARIANCE.P", "COVARIANCE.S",
    "CRITBINOM", "DEVSQ", "EXPON.DIST", "EXPONDIST", "F.DIST",
    "F.DIST.RT", "F.INV", "F.INV.RT", "F.TEST", "FDIST", "FINV",
    "FISHER", "FISHERINV", "FORECAST", "FORECAST.ETS",
    "FORECAST.ETS.CONFINT", "FORECAST.ETS.SEASONALITY",
    "FORECAST.ETS.STAT", "FORECAST.LINEAR", "FREQUENCY", "FTEST",
    "GAMMA", "GAMMA.DIST", "GAMMA.INV", "GAMMADIST", "GAMMAINV",
    "GAMMALN", "GAMMALN.PRECISE", "GAUSS", "GEOMEAN", "GROWTH",
    "HARMEAN", "HYPGEOM.DIST", "HYPGEOMDIST", "INTERCEPT", "KURT",
    "LARGE", "LINEST", "LOGEST", "LOGINV", "LOGNORM.DIST",
    "LOGNORM.INV", "LOGNORMDIST", "MAX", "MAXA", "MAXIFS", "MEDIAN",
    "MIN", "MINA", "MINIFS", "MODE", "MODE.MULT", "MODE.SNGL",
    "NEGBINOM.DIST", "NEGBINOMDIST", "NORM.DIST", "NORM.INV",
    "NORM.S.DIST", "NORM.S.INV", "NORMDIST", "NORMINV", "NORMSDIST",
    "NORMSINV", "PEARSON", "PERCENTILE", "PERCENTILE.EXC",
    "PERCENTILE.INC", "PERCENTRANK", "PERCENTRANK.EXC",
    "PERCENTRANK.INC", "PERMUT", "PERMUTATIONA", "PHI", "POISSON",
    "POISSON.DIST", "PROB", "QUARTILE", "QUARTILE.EXC", "QUARTILE.INC",
    "RANK", "RANK.AVG", "RANK.EQ", "RSQ", "SKEW", "SKEW.P", "SLOPE",
    "SMALL", "STANDARDIZE", "STDEV", "STDEV.P", "STDEV.S", "STDEVA",
    "STDEVP", "STDEVPA", "STEYX", "T.DIST", "T.DIST.2T", "T.DIST.RT",
    "T.INV", "T.INV.2T", "T.TEST", "TDIST", "TINV", "TREND", "TRIMMEAN",
    "TTEST", "VAR", "VAR.P", "VAR.S", "VARA", "VARP", "VARPA",
    "WEIBULL", "WEIBULL.DIST", "ZTEST", "Z.TEST",
    # financial
    "ACCRINT", "ACCRINTM", "AMORDEGRC", "AMORLINC", "COUPDAYBS",
    "COUPDAYS", "COUPDAYSNC", "COUPNCD", "COUPNUM", "COUPPCD",
    "CUMIPMT", "CUMPRINC", "DB", "DDB", "DISC", "DOLLARDE", "DOLLARFR",
    "DURATION", "EFFECT", "FV", "FVSCHEDULE", "INTRATE", "IPMT", "IRR",
    "ISPMT", "MDURATION", "MIRR", "NOMINAL", "NPER", "NPV", "ODDFPRICE",
    "ODDFYIELD", "ODDLPRICE", "ODDLYIELD", "PDURATION", "PMT", "PPMT",
    "PRICE", "PRICEDISC", "PRICEMAT", "PV", "RATE", "RECEIVED", "RRI",
    "SLN", "STOCKHISTORY", "SYD", "TBILLEQ", "TBILLPRICE", "TBILLYIELD",
    "VDB", "XIRR", "XNPV", "YIELD", "YIELDDISC", "YIELDMAT",
    # information
    "CELL", "ERROR.TYPE", "INFO", "ISBLANK", "ISERR", "ISERROR",
    "ISEVEN", "ISFORMULA", "ISLOGICAL", "ISNA", "ISNONTEXT", "ISNUMBER",
    "ISODD", "ISOMITTED", "ISREF", "ISTEXT", "N", "NA", "SHEET",
    "SHEETS", "TYPE",
    # database
    "DAVERAGE", "DCOUNT", "DCOUNTA", "DGET", "DMAX", "DMIN", "DPRODUCT",
    "DSTDEV", "DSTDEVP", "DSUM", "DVAR", "DVARP",
    # engineering
    "BESSELI", "BESSELJ", "BESSELK", "BESSELY", "BIN2DEC", "BIN2HEX",
    "BIN2OCT", "BITAND", "BITLSHIFT", "BITOR", "BITRSHIFT", "BITXOR",
    "COMPLEX", "CONVERT", "DEC2BIN", "DEC2HEX", "DEC2OCT", "DELTA",
    "ERF", "ERF.PRECISE", "ERFC", "ERFC.PRECISE", "GESTEP", "HEX2BIN",
    "HEX2DEC", "HEX2OCT", "IMABS", "IMAGINARY", "IMARGUMENT",
    "IMCONJUGATE", "IMCOS", "IMCOSH", "IMCOT", "IMCSC", "IMCSCH",
    "IMDIV", "IMEXP", "IMLN", "IMLOG10", "IMLOG2", "IMPOWER",
    "IMPRODUCT", "IMREAL", "IMSEC", "IMSECH", "IMSIN", "IMSINH",
    "IMSQRT", "IMSUB", "IMSUM", "IMTAN", "OCT2BIN", "OCT2DEC",
    "OCT2HEX",
    # cube
    "CUBEKPIMEMBER", "CUBEMEMBER", "CUBEMEMBERPROPERTY",
    "CUBERANKEDMEMBER", "CUBESET", "CUBESETCOUNT", "CUBEVALUE",
    # web
    "ENCODEURL", "FILTERXML", "WEBSERVICE",
    # 2023-2025 additions + storage-canonical dynamic-array operators
    # (_xlfn.ANCHORARRAY / _xlfn.SINGLE are how A1# and @ are stored)
    "GROUPBY", "PIVOTBY", "PERCENTOF", "TRIMRANGE", "REGEXTEST",
    "REGEXEXTRACT", "REGEXREPLACE", "TRANSLATE", "DETECTLANGUAGE", "PY",
    "ANCHORARRAY", "SINGLE",
    # legacy compatibility
    "CALL", "EUROCONVERT", "REGISTER.ID",
])
